"""additional card fields

Revision ID: 230bf6bd3b0d
Revises: 9e524fa5775c
Create Date: 2025-06-07 16:53:09.600066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230bf6bd3b0d'
down_revision: Union[str, None] = '9e524fa5775c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('card_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('card_mobile_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('card_job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('card_office_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('card_web', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_card_email'), 'users', ['card_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_card_email'), table_name='users')
    op.drop_column('users', 'card_web')
    op.drop_column('users', 'card_office_phone')
    op.drop_column('users', 'card_job_title')
    op.drop_column('users', 'card_mobile_phone')
    op.drop_column('users', 'card_email')
    op.drop_column('users', 'card_full_name')
    # ### end Alembic commands ###
