"""add phone_prefix to company

Revision ID: 538be9001334
Revises: b5cd021e71f1
Create Date: 2025-06-07 00:51:19.968411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538be9001334'
down_revision: Union[str, None] = 'b5cd021e71f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'phone_prefix')
    # ### end Alembic commands ###
