"""add extra fields

Revision ID: c9676997722e
Revises: 538be9001334
Create Date: 2025-06-07 01:25:56.853304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9676997722e'
down_revision: Union[str, None] = '538be9001334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('web', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('note', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'note')
    op.drop_column('companies', 'web')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
